Repository ONE-TED/5_moduCompany_team1, pull requests merged in 2021-08, with the labels that each got.

#8 [#6] Feat : TodoDate class 구현
  src/utils/todoDate.ts
Labels: feature

#10 [#9] Refactor : TodoDate 클래스 수정
  src/utils/todoDate.ts
Labels: refactor

#15 [#14] Feat: Header 구현
  src/Components/Header/Header.tsx
  src/Components/Header/index.ts
  src/Pages/TodoList/TodoList.tsx
Labels: ✨ feature, 👋 question, 💎 style

#17 [#16] Header 리팩토링
  src/Assets/icons/filter.svg
  src/Assets/index.tsx
  src/Components/Header/Header.tsx
Labels: 🛠 refactor

#22 [#13] Feat : 투두 리스트 create 및 eslint 수정
  .eslintrc.js
  .eslintrc.json
  .prettierrc.js
  package-lock.json
  package.json
  src/Components/Todo/Todocreate/TodoCreate.tsx
  src/Components/Todo/Todocreate/TodoCreateStyle.ts
  src/Components/Todo/Todocreate/index.ts
  src/Hooks/useTodo.tsx
  src/Pages/TodoList/TodoList.tsx
  src/Pages/TodoList/TodoListStyle.ts
  tsconfig.json
Labels: ✨ feature

#25 [#23] Refactor : date class 리팩토링
  src/Components/Header/Header.tsx
  src/Components/Todo/Create/TodoCreate.tsx
  src/utils/todoDate.ts
Labels: 🛠 refactor
